import type { Metadata } from "next";
import "./globals.css";
import React, { FC } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Theme from "@/components/theme";
import dynamic from "next/dynamic";
import Image from "next/image";
import { Toaster } from "sonner";
import Grid2 from "@/components/grid2";
import Grid3 from "@/components/grid3";
import Grid1 from "@/components/grid1";
import Grid4 from "@/components/grid4";

const Clock = dynamic(() => import("@/components/clock"), { ssr: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  x6: React.ReactNode;
  x7: React.ReactNode;
  x8: React.ReactNode;
  x9: React.ReactNode;
  x10: React.ReactNode;
}

const RootLayout: FC<Props> = ({ children, x6, x7, x8, x9, x10 }) => {
  return (
    <html lang="en">
      {/* <html lang="en" suppressHydrationWarning> */}
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="h-screen bg-[#0d0d0d] dark:bg-blue-500 p-5">
            <div className="border-[2.5px] border-[#f8f9f91a] h-full grid grid-cols-12 grid-rows-12 rounded-2xl p-5 gap-4">
              <div className="row-span-4 col-span-5 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-3xl overflow-hidden">
                <Grid1 />
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-4 col-span-4 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                <Grid2 />
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-4 col-span-3 relative overflow-hidden">
                <Grid3 />
              </div>

              <div className="row-span-5 col-span-2 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                <Grid4 />
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-5 col-span-4 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                {x6}
              </div>

              <div className="row-span-5 col-span-3 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                {x7}
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-7 col-span-3 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden p-2">
                {x8}
                {/* <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div> */}
              </div>

              <div className="row-span-3 col-span-5 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                {x9}
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-3 col-span-3 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                {x10}
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-3 col-span-1 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                <Theme />
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>

              <div className="row-span-1 col-span-3 relative border border-[#f8f9f91a] bg-[#f8f9f905] rounded-2xl overflow-hidden">
                <Clock />
                <div className="absolute inset-0 bg-bg1 bg-contain opacity-5 pointer-events-none mix-blend-difference	"></div>
              </div>
            </div>
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
